### ISSUE TITLE
Remove Java specific errors from Editor MSF4J services

### ISSUE THREAD

**Issue by uthaiyashankar** [ballerina-lang/composer#189]
<a href="https://github.com/sumuditha-viraj"><img src="https://avatars.githubusercontent.com/u/6814264?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [sumuditha-viraj](https://github.com/sumuditha-viraj)**
_Friday Jan 27, 2017 at 05:58 GMT_
_Originally opened as https://github.com/ballerinalang/ballerina/issues/1093_

----

We should throw a Ballerina error instead of following Java error.

---------------------
Starting WSO2 Ballerina Tooling (in unsupported JDK)

 [ERROR] WSO2 Ballerina Tooling is supported only on JDK 1.8

Exception in thread "main" java.lang.UnsupportedClassVersionError: org/wso2/ballerina/tooling/service/workspace/app/WorkspaceServiceRunner : Unsupported major.minor version 52.0

at java.lang.ClassLoader.defineClass1(Native Method)

at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)

at java.lang.ClassLoader.defineClass(ClassLoader.java:621)

at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)

at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)

at java.net.URLClassLoader.access$000(URLClassLoader.java:58)

**Comment by hevayo** [comment]
IMO we should not hide java errors for editor back-end services.

**Comment by maheeka** [comment]
Issue still exists for the new fragment parser

**Comment by hevayo** [comment]
Fixed with 0.961.0
