### ISSUE TITLE
Composer went OOM when running infinite loop

### ISSUE THREAD

**Issue by yasassri** [ballerina-lang/composer#3599]
Composer went OOM.
### code 
```ballerina
import ballerina.lang.system;

function main (string[] args) {
    int counter =0;
    while (counter < 500) {
        system:println("yes");
    }
}
```
### Error

java.lang.OutOfMemoryError: GC overhead limit exceeded
Dumping heap to /home/yasassri/QA_STUFF/current_work/0.94Release/ballerina-tools-0.93.1-SNAPSHOT/logs/heap-dump-tool.hprof ...
Heap dump file created [1448246764 bytes in 24.688 secs]
Exception in thread "Thread-7" java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.lang.Class.newReflectionData(Class.java:2511)
	at java.lang.Class.reflectionData(Class.java:2503)
	at java.lang.Class.privateGetDeclaredFields(Class.java:2577)
	at java.lang.Class.getDeclaredFields(Class.java:1916)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:150)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:100)
	at com.google.gson.Gson.getAdapter(Gson.java:423)
	at com.google.gson.Gson.toJson(Gson.java:661)
	at com.google.gson.Gson.toJson(Gson.java:648)
	at com.google.gson.Gson.toJson(Gson.java:603)
	at com.google.gson.Gson.toJson(Gson.java:583)
	at org.ballerinalang.composer.service.workspace.launcher.LaunchManager.pushMessageToClient(LaunchManager.java:295)
	at org.ballerinalang.composer.service.workspace.launcher.LaunchManager.pushMessageToClient(LaunchManager.java:305)
	at org.ballerinalang.composer.service.workspace.launcher.LaunchManager.streamOutput(LaunchManager.java:168)
	at org.ballerinalang.composer.service.workspace.launcher.LaunchManager$1.run(LaunchManager.java:129)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by yasassri** [comment]
**Environment**

Java: 1.8.0_144 (build 1.8.0_144-b01)
Browser: Chrome 58.0.3029.110 (64-bit)

**Comment by hemikak** [comment]
Can we get the ballerina source code for this ?

**Comment by yasassri** [comment]
@hemikak This occurred several times, and the ballerina service was a simple main function with some system outs.  I will share the bal files when this happens again.

**Comment by yasassri** [comment]
I think I was wrong, I could reproduce this issue with the following code snippet. 

```
import ballerina.lang.system;

function main (string[] args) {
    int counter =0;
    while (counter < 500) {
        system:println("yes");
        //system:sleep(50);
    }
}
```
